permaweb/ao-cookbook

- src/tutorials/begin/chatroom.md
- src/tutorials/begin/index.md
- src/tutorials/begin/messaging.md
correcting several errors that involve interactions with Morpheus and Trinity.
> fix: begin tutorial errors

- src/tutorials/begin/chatroom.md
- src/tutorials/begin/messaging.md
- src/tutorials/begin/token.md
added the missing details about Trinity and her posing the next challenge.
> fix: added Trinity's missing details

- src/tutorials/begin/token.md
- src/tutorials/begin/tokengating.md
made several corrections to the token and tokengated tutorials.
> refactor: corrected token and tokengated tutorials

- src/guides/aos/prompt.md
made corrections to the prompt customization guide.
> refactor: corrected prompt customization

- src/tutorials/bots-and-games/announcements.md
- src/tutorials/bots-and-games/ao-effect.md
- src/tutorials/bots-and-games/arena-mechanics.md
- src/tutorials/bots-and-games/build-game.md
- src/tutorials/bots-and-games/game-state.md
> chore: update bots tut

- src/tutorials/begin/tokengating.md
corrected two typos within the tokengated handler.
> fix: corrected tokengating handler

- src/tutorials/begin/tokengating.md
corrected the step in tokengating that was keeping users from getting the exact match data response.
> fix: corrected step in tokengating

- src/tutorials/begin/chatroom.md
- src/tutorials/begin/messaging.md
Just fixing some small things I noticed while going through the `Begin` tutorial content
> Small tweaks in `Begin` tutorial

- src/tutorials/begin/chatroom.md
the chatroom tutorial flowed out of order, so sections had to be reoganized for optimal experience.
> fix: reoganizing the chatroom tutorial

- src/tutorials/begin/messaging.md
- src/tutorials/begin/preparations.md
added videos to Preparations and Messaging.
> feat: adding videos

- src/welcome/index.md
> Update index.md (Wrong link)

- .github/workflows/deploy.yml
- deploy.js
- package.json
Closes #83 
AR.IO team was able to resolve the issue with the file upload, so this just removed the shim code.
> chore: remove manifest shim, as issue is fixed by ar.io #83

- src/tutorials/bots-and-games/build-game.md
.load function requires a *.lua file
> adding *.lua extension on build-game.html

- src/guides/aos/blueprints/token.md
This pull request addresses issue #121 by updating the Token Blueprint code in the AO Cookbook to match the latest code in the AO Stack repository.
**Changes Made:**
- Updated the Token Blueprint code in the AO Cookbook repository.
- Ensured that the updated code aligns with the code in the AO Stack repository.
**Testing:**
- Tested the updated Token Blueprint code to ensure functionality.
- Verified that the code now resolves the issues mentioned in the related issue (#121).
**Related Issue:**
- Closes #121
> fix: Token Blueprint code in AO Cookbook

- src/tutorials/begin/messaging.md
fix the Morpheus variable result.
> fix Morpheus variable result

- src/welcome/testnet-info/cred-and-quests.md
add quests video to the CREDs and Quests page.
> feat: add quests video

- src/tutorials/begin/messaging.md
- src/tutorials/begin/tokengating.md
- src/welcome/testnet-info/cred-and-quests.md
fixed 2 typos pointed out by PBillingsby and removing a duplicate video embed.
> fix: fixing 2 typos and video issue

- src/guides/aos/token.md
i find a spelling error when i read the document
> fix: May be a spelling error, i think

- src/tutorials/begin/token.md
added the begin tutorial build a token video.
> feat: added begin token video

- src/tutorials/begin/preparations.md
- src/tutorials/begin/tokengating.md
Added the tokengating video tutorial to the Begin Tutorial Series.
> feat: tokengating tutorial video

- src/tutorials/bots-and-games/index.md
Added note on Quest 2 no longer paying CRED
> added note about no longer paying CRED

- src/.vitepress/config.js
Hi!
I was a bit frustrated as I couldn't search easily in the docs, so I added the [searchbar vitepress plugin](https://vitepress.dev/reference/default-theme-search)!
It's a small contribution, but I'm sure that it will help everyone.
> feat: add searchbar

- .github/workflows/deploy.yml
- .yarnrc.yml
- deploy.js
- package.json
- src/.vitepress/config.js
- yarn.lock
Also did some housekeeping:
- bumped dependencies
- remove duplicate `themeConfig` from `vitepress` config
> ci(ant): use ario sdk and ao process to update ANT

- src/concepts/messages.md
- src/concepts/processes.md
Documents behavior implemented as part of https://github.com/permaweb/ao/issues/862
> feat(concepts): add section for Ethereum signed processes, modules, and messages

- src/guides/aos/blueprints/token.md
Updates `token.md` with the latest version on the Token blueprint. Adds summaries of the totalSupply and burn handlers.
> fix(cookbook): update token blueprint code with latest version #191

- src/references/ao.md
> feat(cookbook): mention the authority tag #214

- languages/strings/en.json
- languages/strings/zh.json
- src/.vitepress/locales.js
- src/references/community.md
- src/references/editor-setup.md
- src/zh/references/community.md
Mention community partners in the ao cookbook
Closes #320
> feat(cookbook): create community section for partners #320

- src/tutorials/begin/chatroom.md
Morpheus would not respond without this change
> Fix "Registered" Capitalization

- src/releasenotes/aos-2_0_0.md
- src/releasenotes/aos-2_0_1.md
fixes aos 2.0.0 release notes content to be accurate
> docs: fix aos 2.0.0 release notes

- src/releasenotes/aos-2_0_0.md
- src/tutorials/begin/preparations.md
- src/tutorials/bots-and-games/ao-effect.md
- src/welcome/getting-started.md
- src/welcome/legacynet-info/index.md
The current gateway (g8way.io) is heavily flagged on VirusTotal- switching to the cleaner arweave.net gateway
> Switching to arweave.net gateway

- src/llms-explanation.md
- src/public/ja/llms-full.txt
- src/public/ja/llms.txt
- src/public/llms-full.txt
- src/public/llms.txt
- src/public/zh/llms-full.txt
- src/public/zh/llms.txt
This PR introduces the following changes compared to the main branch:
**Embeded Permaweb LLMs.txt Builder Tool:**  
- Added a new section to `src/llms-explanation.md` that introduces and embeds the [Permaweb LLMs.txt Builder Tool](https://permaweb-llms-builder.arweave.net).
- The embed includes both light and dark mode iframes, with appropriate CSS to toggle visibility based on the user's theme.
- The new section in `llms-explanation.md` provides users with a direct, interactive way to build custom LLMs.txt files from Permaweb ecosystem docs.
- The iframe embed is responsive and theme-aware, ensuring a seamless user experience in both light and dark modes.
- The LLMs documentation files have been regenerated to reflect the latest content and generation timestamps.
- Improves …
> Add Permaweb LLMs.txt iframe and Update LLMs Documentation Files
